services:
  api:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_OWNER=${MYSQL_OWNER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

volumes:
  api_data:

